name:   'ERP.im'
url:    'http://ERP.im'
author: 'ERPIM'

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

safe:     true
pygments: false
markdown: 'kramdown'
timezone: 'America/Chicago'
