permalink: /:year/:month/:day/:title.html
paginate: 1
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: ERP.im
  email: hi@erp.im
  link: http://erp.im

# 站点信息
title: ERP.im
description: ERP.im
url: http://ERP.im
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://ERP.im/public/img/gavatar.png
favicon: http://ERP.im/public/img/favicon.ico

# google analytics 设置
ga:
  id: UA-39939963-2
  url: ERP.im

# disqus 设置
disqus:
  shortname: erpim
